[application]
name = "AnyTask"

[web.app]
title = "AnyTask"

# include `assets` in web platform
# [web.resource]

# Additional CSS style files
style = []

[bundle]
identifier = "com.Tumypmyp.AnyTask"
publisher = "Tumypmyp"
icon = ["assets/favicon.ico"]
category = "Productivity"
short_description = "Cross-Platform Anytype client"

[bundle.windows]
icon_path = "assets/favicon.ico"

[bundle.windows.webview_install_mode.EmbedBootstrapper]
silent = true
