# --- Main Configuration Section ---
[global]
log_level = "debug"

# --- HTTP Listener (The Incoming Port) ---
[[listeners]]
address = "0.0.0.0:31029"
protocol = "http"

# --- Backend Cluster (Group of Servers) ---
[clusters]
[clusters.servers]
protocol = "http"
frontends = [
    {address = "0.0.0.0:31029", hostname = "*"}
]
backends = [
    { address = "127.0.0.1:31009"}
]

# --- HTTP Router (Routing Rule) ---
[routers]
name = "app_router"
rule = "HostRegexp(`.*`)"
cluster_name = "host_app_cluster"
listener_name = "http_in"
